[  0] = "sys_restart_syscall"
[  1] = "sys_exit" U_NB
[  2] = "sys_fork" struct pt_regs *	-	-	-	-	arch/alpha/kernel/entry.S:716
[  3] = "sys_read" unsigned int fd	char __user *buf	size_t count	-	-	fs/read_write.c:391
[  4] = "sys_write" unsigned int fd	const char __user *buf	size_t count	-	-	fs/read_write.c:408
[  5] = "sys_open" const char __user *filename	int flags	int mode	-	-	fs/open.c:900
[  6] = "sys_close" unsigned int fd	-	-	-	-	fs/open.c:969
[  7] = "sys_waitpid" pid_t pid	int __user *stat_addr	int options	-	-	kernel/exit.c:1771
[  8] = "sys_creat" const char __user *pathname	int mode	-	-	-	fs/open.c:933
[  9] = "sys_link" const char __user *oldname	const char __user *newname	-	-	-	fs/namei.c:2520
[ 10] = "sys_unlink" const char __user *pathname	-	-	-	-	fs/namei.c:2352
[ 11] = "sys_execve" char __user *	char __user *__user *	char __user *__user *	struct pt_regs *	-	arch/alpha/kernel/entry.S:925
[ 12] = "sys_chdir" const char __user *filename	-	-	-	-	fs/open.c:361
[ 13] = "sys_time" time_t __user *tloc	-	-	-	-	kernel/posix-timers.c:855
[ 14] = "sys_mknod" const char __user *filename	int mode	unsigned dev	-	-	fs/namei.c:2067
[ 15] = "sys_chmod" const char __user *filename	mode_t mode	-	-	-	fs/open.c:507
[ 16] = "sys_lchown16" const char __user *filename	old_uid_t user	old_gid_t group	-	-	kernel/uid16.c:27
[ 17] = "not" implemented -	-	-	-	-	
[ 18] = "sys_stat" char __user *filename	struct __old_kernel_stat __user *statbuf	-	-	-	fs/stat.c:150
[ 19] = "sys_lseek" unsigned int fd	off_t offset	unsigned int origin	-	-	fs/read_write.c:167
[ 20] = "sys_getpid" -	-	-	-	-	kernel/timer.c:1337
[ 21] = "sys_mount" char __user *dev_name	char __user *dir_name	char __user *type	unsigned long flags	void __user *data	fs/namespace.c:2118
[ 22] = "sys_oldumount" char __user *name	-	-	-	-	fs/namespace.c:1171
[ 23] = "sys_setuid16" old_uid_t uid	-	-	-	-	kernel/uid16.c:67
[ 24] = "sys_getuid16" -	-	-	-	-	kernel/uid16.c:212
[ 25] = "sys_stime" time_t __user *tptr	-	-	-	-	kernel/time.c:81
[ 26] = "sys_ptrace" long request	long pid	long addr	long data	-	kernel/ptrace.c:688
[ 27] = "sys_alarm" unsigned int seconds	-	-	-	-	kernel/timer.c:1314
[ 28] = "sys_fstat" unsigned int fd	struct __old_kernel_stat __user *statbuf	-	-	-	fs/stat.c:174
[ 29] = "sys_pause" -	-	-	-	-	kernel/signal.c:2700
[ 30] = "sys_utime" char __user *filename	struct utimbuf __user *times	-	-	-	fs/utimes.c:27
[ 31] = "not" implemented -	-	-	-	-	
[ 32] = "not" implemented -	-	-	-	-	
[ 33] = "sys_access" const char __user *filename	int mode	-	-	-	fs/open.c:356
[ 34] = "sys_nice" int increment	-	-	-	-	kernel/sched.c:4282
[ 35] = "not" implemented -	-	-	-	-	
[ 36] = "sys_sync" -	-	-	-	-	fs/sync.c:98
[ 37] = "sys_kill" int pid	int sig	-	-	-	kernel/signal.c:2317
[ 38] = "sys_rename" const char __user *oldname	const char __user *newname	-	-	-	fs/namei.c:2765
[ 39] = "sys_mkdir" const char __user *pathname	int mode	-	-	-	fs/namei.c:2130
[ 40] = "sys_rmdir" const char __user *pathname	-	-	-	-	fs/namei.c:2244
[ 41] = "sys_dup" unsigned int fildes	-	-	-	-	fs/fcntl.c:131
[ 42] = "sys_pipe" int __user *fildes	-	-	-	-	fs/pipe.c:1117
[ 43] = "sys_times" struct tms __user *tbuf	-	-	-	-	kernel/sys.c:896
[ 44] = "not" implemented -	-	-	-	-	
[ 45] = "sys_brk" unsigned long brk	-	-	-	-	mm/mmap.c:245
[ 46] = "sys_setgid16" old_gid_t gid	-	-	-	-	kernel/uid16.c:51
[ 47] = "sys_getgid16" -	-	-	-	-	kernel/uid16.c:222
[ 48] = "sys_signal" int sig	__sighandler_t handler	-	-	-	kernel/signal.c:2683
[ 49] = "sys_geteuid16" -	-	-	-	-	kernel/uid16.c:217
[ 50] = "sys_getegid16" -	-	-	-	-	kernel/uid16.c:227
[ 51] = "sys_acct" const char __user *name	-	-	-	-	kernel/acct.c:274
[ 52] = "sys_umount" char __user *name	int flags	-	-	-	fs/namespace.c:1132
[ 53] = "not" implemented -	-	-	-	-	
[ 54] = "sys_ioctl" unsigned int fd	unsigned int cmd	unsigned long arg	-	-	fs/ioctl.c:613
[ 55] = "sys_fcntl" unsigned int fd	unsigned int cmd	unsigned long arg	-	-	fs/fcntl.c:429
[ 56] = "not" implemented -	-	-	-	-	
[ 57] = "sys_setpgid" pid_t pid	pid_t pgid	-	-	-	kernel/sys.c:921
[ 58] = "not" implemented -	-	-	-	-	
[ 59] = "sys_olduname" struct oldold_utsname __user *	-	-	-	-	kernel/sys.c:1132
[ 60] = "sys_umask" int mask	-	-	-	-	kernel/sys.c:1460
[ 61] = "sys_chroot" const char __user *filename	-	-	-	-	fs/open.c:408
[ 62] = "sys_ustat" unsigned dev	struct ustat __user *ubuf	-	-	-	fs/statfs.c:175
[ 63] = "sys_dup2" unsigned int oldfd	unsigned int newfd	-	-	-	fs/fcntl.c:116
[ 64] = "sys_getppid" -	-	-	-	-	kernel/timer.c:1348
[ 65] = "sys_getpgrp" -	-	-	-	-	kernel/sys.c:1020
[ 66] = "sys_setsid" -	-	-	-	-	kernel/sys.c:1055
[ 67] = "sys_sigaction" int sig	const struct old_sigaction __user *act	struct old_sigaction __user *oact	-	-	arch/mips/kernel/signal.c:300
[ 68] = "sys_sgetmask" -	-	-	-	-	kernel/signal.c:2657
[ 69] = "sys_ssetmask" int newmask	-	-	-	-	kernel/signal.c:2663
[ 70] = "sys_setreuid16" old_uid_t ruid	old_uid_t euid	-	-	-	kernel/uid16.c:59
[ 71] = "sys_setregid16" old_gid_t rgid	old_gid_t egid	-	-	-	kernel/uid16.c:43
[ 72] = "sys_sigsuspend" int history0	int history1	old_sigset_t mask	-	-	arch/s390/kernel/signal.c:58
[ 73] = "sys_sigpending" old_sigset_t __user *set	-	-	-	-	kernel/signal.c:2562
[ 74] = "sys_sethostname" char __user *name	int len	-	-	-	kernel/sys.c:1165
[ 75] = "sys_setrlimit" unsigned int resource	struct rlimit __user *rlim	-	-	-	kernel/sys.c:1275
[ 76] = "sys_old_getrlimit" unsigned int resource	struct rlimit __user *rlim	-	-	-	kernel/sys.c:1256
[ 77] = "sys_getrusage" int who	struct rusage __user *ru	-	-	-	kernel/sys.c:1452
[ 78] = "sys_gettimeofday" struct timeval __user *tv	struct timezone __user *tz	-	-	-	kernel/time.c:101
[ 79] = "sys_settimeofday" struct timeval __user *tv	struct timezone __user *tz	-	-	-	kernel/time.c:185
[ 80] = "sys_getgroups16" int gidsetsize	old_gid_t __user *grouplist	-	-	-	kernel/uid16.c:164
[ 81] = "sys_setgroups16" int gidsetsize	old_gid_t __user *grouplist	-	-	-	kernel/uid16.c:187
[ 82] = "sys_old_select" struct sel_arg_struct __user *arg	-	-	-	-	fs/select.c:701
[ 83] = "sys_symlink" const char __user *old	const char __user *new	-	-	-	fs/namei.c:2419
[ 84] = "sys_lstat" char __user *filename	struct __old_kernel_stat __user *statbuf	-	-	-	fs/stat.c:162
[ 85] = "sys_readlink" const char __user *path	char __user *buf	int bufsiz	-	-	fs/stat.c:311
[ 86] = "sys_uselib" const char __user *library	-	-	-	-	fs/exec.c:107
[ 87] = "sys_swapon" const char __user *specialfile	int swap_flags	-	-	-	mm/swapfile.c:1793
[ 88] = "sys_reboot" int magic1	int magic2	unsigned int cmd	void __user *arg	-	kernel/sys.c:368
[ 89] = "sys_old_readdir" unsigned int	struct old_linux_dirent __user *	unsigned int	-	-	fs/readdir.c:105
[ 90] = "sys_old_mmap" struct mmap_arg_struct __user *arg	-	-	-	-	mm/mmap.c:1141
[ 91] = "sys_munmap" unsigned long addr	size_t len	-	-	-	mm/mmap.c:2109
[ 92] = "sys_truncate" const char __user *path	long length	-	-	-	fs/open.c:127
[ 93] = "sys_ftruncate" unsigned int fd	unsigned long length	-	-	-	fs/open.c:178
[ 94] = "sys_fchmod" unsigned int fd	mode_t mode	-	-	-	fs/open.c:436
[ 95] = "sys_fchown16" unsigned int fd	old_uid_t user	old_gid_t group	-	-	kernel/uid16.c:35
[ 96] = "sys_getpriority" int which	int who	-	-	-	kernel/sys.c:216
[ 97] = "sys_setpriority" int which	int who	int niceval	-	-	kernel/sys.c:149
[ 98] = "not" implemented -	-	-	-	-	
[ 99] = "sys_statfs" const char __user * path	struct statfs __user *buf	-	-	-	fs/statfs.c:102
[100] = "sys_fstatfs" unsigned int fd	struct statfs __user *buf	-	-	-	fs/statfs.c:136
[101] = "sys_ioperm" unsigned long	unsigned long	int	-	-	not found:
[102] = "sys_socketcall" int call	unsigned long __user *args	-	-	-	net/socket.c:2210
[103] = "sys_syslog" int type	char __user *buf	int len	-	-	kernel/printk.c:412
[104] = "sys_setitimer" int which	struct itimerval __user *value	struct itimerval __user *ovalue	-	-	kernel/itimer.c:279
[105] = "sys_getitimer" int which	struct itimerval __user *value	-	-	-	kernel/itimer.c:103
[106] = "sys_newstat" char __user *filename	struct stat __user *statbuf	-	-	-	fs/stat.c:237
[107] = "sys_newlstat" char __user *filename	struct stat __user *statbuf	-	-	-	fs/stat.c:247
[108] = "sys_newfstat" unsigned int fd	struct stat __user *statbuf	-	-	-	fs/stat.c:273
[109] = "sys_uname" struct old_utsname __user *	-	-	-	-	kernel/sys.c:1115
[110] = "sys_iopl" unsigned int	struct pt_regs *	-	-	-	not found:
[111] = "sys_vhangup" -	-	-	-	-	fs/open.c:1008
[112] = "not" implemented -	-	-	-	-	
[113] = "sys_vm86old" struct vm86_struct __user *	struct pt_regs *	-	-	-	not found:
[114] = "sys_wait4" pid_t pid	int __user *stat_addr	int options	struct rusage __user *ru	-	kernel/exit.c:1726
[115] = "sys_swapoff" const char __user *specialfile	-	-	-	-	mm/swapfile.c:1533
[116] = "sys_sysinfo" struct sysinfo __user *info	-	-	-	-	kernel/timer.c:1565
[117] = "sys_ipc" -	-	-	-	-	ipc/syscall.c:16
[118] = "sys_fsync" unsigned int fd	-	-	-	-	fs/sync.c:221
[119] = "sys_sigreturn" struct pt_regs *regs	-	-	-	-	arch/alpha/kernel/entry.S:758
[120] = "sys_clone" unsigned long	unsigned long	unsigned long	unsigned long	struct pt_regs *	arch/alpha/kernel/entry.S:733
[121] = "sys_setdomainname" char __user *name	int len	-	-	-	kernel/sys.c:1214
[122] = "sys_newuname" struct new_utsname __user *name	-	-	-	-	kernel/sys.c:1097
[123] = "sys_modify_ldt" int	void __user *	unsigned long	-	-	not found:
[124] = "sys_adjtimex" struct timex __user *txc_p	-	-	-	-	kernel/time.c:206
[125] = "sys_mprotect" unsigned long start	size_t len	unsigned long prot	-	-	mm/mprotect.c:221
[126] = "sys_sigprocmask" int how	old_sigset_t __user *set	old_sigset_t __user *oset	-	-	kernel/signal.c:2573
[127] = "not" implemented -	-	-	-	-	
[128] = "sys_init_module" void __user *umod	unsigned long len	const char __user *uargs	-	-	kernel/module.c:2611
[129] = "sys_delete_module" const char __user *name_user	unsigned int flags	-	-	-	kernel/module.c:720
[130] = "not" implemented -	-	-	-	-	
[131] = "sys_quotactl" unsigned int cmd	const char __user *special	qid_t id	void __user *addr	-	fs/quota/quota.c:333
[132] = "sys_getpgid" pid_t pid	-	-	-	-	kernel/sys.c:990
[133] = "sys_fchdir" unsigned int fd	-	-	-	-	fs/open.c:382
[134] = "sys_bdflush" int func	long data	-	-	-	fs/buffer.c:3278
[135] = "sys_sysfs" int option	unsigned long arg1	unsigned long arg2	-	-	fs/filesystems.c:182
[136] = "sys_personality" unsigned int personality	-	-	-	-	kernel/exec_domain.c:191
[137] = "not" implemented -	-	-	-	-	
[138] = "sys_setfsuid16" old_uid_t uid	-	-	-	-	kernel/uid16.c:118
[139] = "sys_setfsgid16" old_gid_t gid	-	-	-	-	kernel/uid16.c:126
[140] = "sys_llseek" unsigned int fd	unsigned long offset_high	unsigned long offset_low	loff_t __user *result	unsigned int origin	fs/read_write.c:191
[141] = "sys_getdents" unsigned int fd	struct linux_dirent __user *dirent	unsigned int count	-	-	fs/readdir.c:191
[142] = "sys_select" int n	fd_set __user *inp	fd_set __user *outp	fd_set __user *exp	struct timeval __user *tvp	fs/select.c:596
[143] = "sys_flock" unsigned int fd	unsigned int cmd	-	-	-	fs/locks.c:1569
[144] = "sys_msync" unsigned long start	size_t len	int flags	-	-	mm/msync.c:31
[145] = "sys_readv" unsigned long fd	const struct iovec __user *vec	unsigned long vlen	-	-	fs/read_write.c:711
[146] = "sys_writev" unsigned long fd	const struct iovec __user *vec	unsigned long vlen	-	-	fs/read_write.c:732
[147] = "sys_getsid" pid_t pid	-	-	-	-	kernel/sys.c:1027
[148] = "sys_fdatasync" unsigned int fd	-	-	-	-	fs/sync.c:226
[149] = "sys_sysctl" struct __sysctl_args __user *args	-	-	-	-	kernel/sysctl_binary.c:1462
[150] = "sys_mlock" unsigned long start	size_t len	-	-	-	mm/mlock.c:491
[151] = "sys_munlock" unsigned long start	size_t len	-	-	-	mm/mlock.c:519
[152] = "sys_mlockall" int flags	-	-	-	-	mm/mlock.c:556
[153] = "sys_munlockall" -	-	-	-	-	mm/mlock.c:584
[154] = "sys_sched_setparam" pid_t pid	struct sched_param __user *param	-	-	-	kernel/sched.c:4616
[155] = "sys_sched_getparam" pid_t pid	struct sched_param __user *param	-	-	-	kernel/sched.c:4651
[156] = "sys_sched_setscheduler" pid_t pid	int policy	struct sched_param __user *param	-	-	kernel/sched.c:4601
[157] = "sys_sched_getscheduler" pid_t pid	-	-	-	-	kernel/sched.c:4625
[158] = "sys_sched_yield" -	-	-	-	-	kernel/sched.c:4851
[159] = "sys_sched_get_priority_max" int policy	-	-	-	-	kernel/sched.c:4989
[160] = "sys_sched_get_priority_min" int policy	-	-	-	-	kernel/sched.c:5014
[161] = "sys_sched_rr_get_interval" pid_t pid	struct timespec __user *interval	-	-	-	kernel/sched.c:5039
[162] = "sys_nanosleep" struct timespec __user *rqtp	struct timespec __user *rmtp	-	-	-	kernel/hrtimer.c:1606
[163] = "sys_mremap" unsigned long addr	unsigned long old_len	unsigned long new_len	unsigned long flags	unsigned long new_addr	mm/mremap.c:510
[164] = "sys_setresuid16" old_uid_t ruid	old_uid_t euid	old_uid_t suid	-	-	kernel/uid16.c:75
[165] = "sys_getresuid16" old_uid_t __user *ruid	old_uid_t __user *euid	old_uid_t __user *suid	-	-	kernel/uid16.c:84
[166] = "sys_vm86" unsigned long	unsigned long	struct pt_regs *	-	-	not found:
[167] = "not" implemented -	-	-	-	-	
[168] = "sys_poll" struct pollfd __user *ufds	unsigned int nfds	long timeout	-	-	fs/select.c:915
[169] = "sys_nfsservctl" int cmd	struct nfsctl_arg __user *arg	void __user *res	-	-	fs/nfsctl.c:86
[170] = "sys_setresgid16" old_gid_t rgid	old_gid_t egid	old_gid_t sgid	-	-	kernel/uid16.c:96
[171] = "sys_getresgid16" old_gid_t __user *rgid	old_gid_t __user *egid	old_gid_t __user *sgid	-	-	kernel/uid16.c:106
[172] = "sys_prctl" int option	unsigned long arg2	unsigned long arg3	unsigned long arg4	unsigned long arg5	kernel/sys.c:1466
[173] = "sys_rt_sigreturn" struct pt_regs *	-	-	-	-	arch/alpha/kernel/entry.S:771
[174] = "sys_rt_sigaction" int sig	const struct sigaction __user *act	struct sigaction __user *oact	size_t sigsetsize	-	kernel/signal.c:2624
[175] = "sys_rt_sigprocmask" int how	sigset_t __user *set	sigset_t __user *oset	size_t sigsetsize	-	kernel/signal.c:2111
[176] = "sys_rt_sigpending" sigset_t __user *set	size_t sigsetsize	-	-	-	kernel/signal.c:2171
[177] = "sys_rt_sigtimedwait" const sigset_t __user *uthese	siginfo_t __user *uinfo	const struct timespec __user *uts	size_t sigsetsize	-	kernel/signal.c:2242
[178] = "sys_rt_sigqueueinfo" int pid	int sig	siginfo_t __user *uinfo	-	-	kernel/signal.c:2404
[179] = "sys_rt_sigsuspend" sigset_t __user *unewset	size_t sigsetsize	-	-	-	kernel/signal.c:2710
[180] = "sys_pread64" unsigned int fd	char __user *buf	size_t count	loff_t pos	-	not found:
[181] = "sys_pwrite64" unsigned int fd	const char __user *buf	size_t count	loff_t pos	-	not found:
[182] = "sys_chown16" const char __user *filename	old_uid_t user	old_gid_t group	-	-	kernel/uid16.c:19
[183] = "sys_getcwd" char __user *buf	unsigned long size	-	-	-	fs/dcache.c:2104
[184] = "sys_capget" cap_user_header_t header	cap_user_data_t dataptr	-	-	-	kernel/capability.c:161
[185] = "sys_capset" cap_user_header_t header	const cap_user_data_t data	-	-	-	kernel/capability.c:235
[186] = "sys_sigaltstack" const stack_t __user *	stack_t __user *	struct pt_regs *	-	-	arch/alpha/kernel/signal.c:199
[187] = "sys_sendfile" int out_fd	int in_fd	off_t __user *offset	size_t count	-	fs/read_write.c:897
[188] = "not" implemented -	-	-	-	-	
[189] = "not" implemented -	-	-	-	-	
[190] = "sys_vfork" struct pt_regs *	-	-	-	-	arch/alpha/kernel/entry.S:746
[191] = "sys_getrlimit" unsigned int resource	struct rlimit __user *rlim	-	-	-	kernel/sys.c:1237
[192] = "sys_mmap_pgoff" -	-	-	-	-	mm/mmap.c:1091
[193] = "sys_truncate64" const char __user *path	loff_t length	-	-	-	not found:
[194] = "sys_ftruncate64" unsigned int fd	loff_t length	-	-	-	not found:
[195] = "sys_stat64" char __user *filename	struct stat64 __user *statbuf	-	-	-	fs/stat.c:358
[196] = "sys_lstat64" char __user *filename	struct stat64 __user *statbuf	-	-	-	fs/stat.c:369
[197] = "sys_fstat64" unsigned long fd	struct stat64 __user *statbuf	-	-	-	fs/stat.c:380
[198] = "sys_lchown" const char __user *filename	uid_t user	gid_t group	-	-	fs/open.c:583
[199] = "sys_getuid" -	-	-	-	-	kernel/timer.c:1359
[200] = "sys_getgid" -	-	-	-	-	kernel/timer.c:1371
[201] = "sys_geteuid" -	-	-	-	-	kernel/timer.c:1365
[202] = "sys_getegid" -	-	-	-	-	kernel/timer.c:1377
[203] = "sys_setreuid" uid_t ruid	uid_t euid	-	-	-	kernel/sys.c:594
[204] = "sys_setregid" gid_t rgid	gid_t egid	-	-	-	kernel/sys.c:484
[205] = "sys_getgroups" int gidsetsize	gid_t __user *grouplist	-	-	-	kernel/groups.c:203
[206] = "sys_setgroups" int gidsetsize	gid_t __user *grouplist	-	-	-	kernel/groups.c:232
[207] = "sys_fchown" unsigned int fd	uid_t user	gid_t group	-	-	fs/open.c:602
[208] = "sys_setresuid" uid_t ruid	uid_t euid	uid_t suid	-	-	kernel/sys.c:696
[209] = "sys_getresuid" uid_t __user *ruid	uid_t __user *euid	uid_t __user *suid	-	-	kernel/sys.c:746
[210] = "sys_setresgid" gid_t rgid	gid_t egid	gid_t sgid	-	-	kernel/sys.c:761
[211] = "sys_getresgid" gid_t __user *rgid	gid_t __user *egid	gid_t __user *sgid	-	-	kernel/sys.c:800
[212] = "sys_chown" const char __user *filename	uid_t user	gid_t group	-	-	fs/open.c:539
[213] = "sys_setuid" uid_t uid	-	-	-	-	kernel/sys.c:655
[214] = "sys_setgid" gid_t gid	-	-	-	-	kernel/sys.c:531
[215] = "sys_setfsuid" uid_t uid	-	-	-	-	kernel/sys.c:819
[216] = "sys_setfsgid" gid_t gid	-	-	-	-	kernel/sys.c:852
[217] = "sys_pivot_root" const char __user *new_root	const char __user *put_old	-	-	-	fs/namespace.c:2184
[218] = "sys_mincore" unsigned long start	size_t len	unsigned char __user * vec	-	-	mm/mincore.c:256
[219] = "sys_madvise" unsigned long start	size_t len	int behavior	-	-	mm/madvise.c:335
[220] = "sys_getdents64" unsigned int fd	struct linux_dirent64 __user *dirent	unsigned int count	-	-	fs/readdir.c:273
[221] = "sys_fcntl64" unsigned int fd	unsigned int cmd	unsigned long arg	-	-	fs/fcntl.c:452
[222] = "not" implemented -	-	-	-	-	
[223] = "not" implemented -	-	-	-	-	
[224] = "sys_gettid" -	-	-	-	-	kernel/timer.c:1493
[225] = "sys_readahead" int fd	loff_t offset	size_t count	-	-	not found:
[226] = "sys_setxattr" const char __user *path	const char __user *name	const void __user *value	size_t size	int flags	fs/xattr.c:279
[227] = "sys_lsetxattr" const char __user *path	const char __user *name	const void __user *value	size_t size	int flags	fs/xattr.c:298
[228] = "sys_fsetxattr" int fd	const char __user *name	const void __user *value	size_t size	int flags	fs/xattr.c:317
[229] = "sys_getxattr" const char __user *path	const char __user *name	void __user *value	size_t size	-	fs/xattr.c:376
[230] = "sys_lgetxattr" const char __user *path	const char __user *name	void __user *value	size_t size	-	fs/xattr.c:390
[231] = "sys_fgetxattr" int fd	const char __user *name	void __user *value	size_t size	-	fs/xattr.c:404
[232] = "sys_listxattr" const char __user *path	char __user *list	size_t size	-	-	fs/xattr.c:449
[233] = "sys_llistxattr" const char __user *path	char __user *list	size_t size	-	-	fs/xattr.c:463
[234] = "sys_flistxattr" int fd	char __user *list	size_t size	-	-	fs/xattr.c:477
[235] = "sys_removexattr" const char __user *path	const char __user *name	-	-	-	fs/xattr.c:509
[236] = "sys_lremovexattr" const char __user *path	const char __user *name	-	-	-	fs/xattr.c:527
[237] = "sys_fremovexattr" int fd	const char __user *name	-	-	-	fs/xattr.c:545
[238] = "sys_tkill" int pid	int sig	-	-	-	kernel/signal.c:2395
[239] = "sys_sendfile64" int out_fd	int in_fd	loff_t __user *offset	size_t count	-	fs/read_write.c:916
[240] = "sys_futex" -	-	-	-	-	kernel/futex.c:2605
[241] = "sys_sched_setaffinity" pid_t pid	unsigned int len	unsigned long __user *user_mask_ptr	-	-	kernel/sched.c:4765
[242] = "sys_sched_getaffinity" pid_t pid	unsigned int len	unsigned long __user *user_mask_ptr	-	-	kernel/sched.c:4817
[243] = "sys_set_thread_area" struct user_desc __user *	-	-	-	-	arch/mips/kernel/syscall.c:222
[244] = "sys_get_thread_area" struct user_desc __user *	-	-	-	-	not found:
[245] = "sys_io_setup" unsigned nr_reqs	aio_context_t __user *ctx	-	-	-	fs/aio.c:1245
[246] = "sys_io_destroy" aio_context_t ctx	-	-	-	-	fs/aio.c:1283
[247] = "sys_io_getevents" aio_context_t ctx_id	long min_nr	long nr	struct io_event __user *events	struct timespec __user *timeout	fs/aio.c:1808
[248] = "sys_io_submit" aio_context_t	long	struct iocb __user * __user *	-	-	fs/aio.c:1711
[249] = "sys_io_cancel" aio_context_t ctx_id	struct iocb __user *iocb	struct io_event __user *result	-	-	fs/aio.c:1746
[250] = "sys_fadvise64" int fd	loff_t offset	size_t len	int advice	-	not found:
[251] = "not" implemented -	-	-	-	-	
[252] = "sys_exit_group" int error_code	-	-	-	-	kernel/exit.c:1087
[253] = "sys_lookup_dcookie" u64 cookie64	char __user *buf	size_t len	-	-	not found:
[254] = "sys_epoll_create" int size	-	-	-	-	fs/eventpoll.c:1215
[255] = "sys_epoll_ctl" int epfd	int op	int fd	struct epoll_event __user *event	-	fs/eventpoll.c:1228
[256] = "sys_epoll_wait" int epfd	struct epoll_event __user *events	int maxevents	int timeout	-	fs/eventpoll.c:1320
[257] = "sys_remap_file_pages" unsigned long start	unsigned long size	unsigned long prot	unsigned long pgoff	unsigned long flags	mm/fremap.c:123
[258] = "sys_set_tid_address" int __user *tidptr	-	-	-	-	kernel/fork.c:920
[259] = "sys_timer_create" clockid_t which_clock	struct sigevent __user *timer_event_spec	timer_t __user * created_timer_id	-	-	kernel/posix-timers.c:522
[260] = "sys_timer_settime" timer_t timer_id	int flags	const struct itimerspec __user *new_setting	struct itimerspec __user *old_setting	-	kernel/posix-timers.c:800
[261] = "sys_timer_gettime" timer_t timer_id	struct itimerspec __user *setting	-	-	-	kernel/posix-timers.c:702
[262] = "sys_timer_getoverrun" timer_t timer_id	-	-	-	-	kernel/posix-timers.c:732
[263] = "sys_timer_delete" timer_t timer_id	-	-	-	-	kernel/posix-timers.c:855
[264] = "sys_clock_settime" clockid_t which_clock	const struct timespec __user *tp	-	-	-	kernel/posix-timers.c:941
[265] = "sys_clock_gettime" clockid_t which_clock	struct timespec __user *tp	-	-	-	kernel/posix-timers.c:954
[266] = "sys_clock_getres" clockid_t which_clock	struct timespec __user *tp	-	-	-	kernel/posix-timers.c:971
[267] = "sys_clock_nanosleep" clockid_t which_clock	int flags	const struct timespec __user *rqtp	struct timespec __user *rmtp	-	kernel/posix-timers.c:1001
[268] = "sys_statfs64" const char __user *path	size_t sz	struct statfs64 __user *buf	-	-	fs/statfs.c:118
[269] = "sys_fstatfs64" unsigned int fd	size_t sz	struct statfs64 __user *buf	-	-	fs/statfs.c:154
[270] = "sys_tgkill" int tgid	int pid	int sig	-	-	kernel/signal.c:2383
[271] = "sys_utimes" char __user *filename	struct timeval __user *utimes	-	-	-	fs/utimes.c:219
[272] = "sys_fadvise64_64" int fd	loff_t offset	loff_t len	int advice	-	not found:
[273] = "not" implemented -	-	-	-	-	
[274] = "sys_mbind" -	-	-	-	-	mm/mempolicy.c:1232
[275] = "sys_get_mempolicy" int __user *policy	unsigned long __user *nmask	unsigned long maxnode	unsigned long addr	unsigned long flags	mm/mempolicy.c:1348
[276] = "sys_set_mempolicy" int mode	unsigned long __user *nmask	unsigned long maxnode	-	-	mm/mempolicy.c:1254
[277] = "sys_mq_open" const char __user *name	int oflag	mode_t mode	struct mq_attr __user *attr	-	ipc/mqueue.c:673
[278] = "sys_mq_unlink" const char __user *name	-	-	-	-	ipc/mqueue.c:746
[279] = "sys_mq_timedsend" mqd_t mqdes	const char __user *msg_ptr	size_t msg_len	unsigned int msg_prio	const struct timespec __user *abs_timeout	ipc/mqueue.c:840
[280] = "sys_mq_timedreceive" mqd_t mqdes	char __user *msg_ptr	size_t msg_len	unsigned int __user *msg_prio	const struct timespec __user *abs_timeout	ipc/mqueue.c:934
[281] = "sys_mq_notify" mqd_t mqdes	const struct sigevent __user *notification	-	-	-	ipc/mqueue.c:1023
[282] = "sys_mq_getsetattr" mqd_t mqdes	const struct mq_attr __user *mqstat	struct mq_attr __user *omqstat	-	-	ipc/mqueue.c:1154
[283] = "sys_kexec_load" unsigned long entry	unsigned long nr_segments	struct kexec_segment __user *segments	unsigned long flags	-	kernel/kexec.c:939
[284] = "sys_waitid" int which	pid_t pid	struct siginfo __user *infop	int options	struct rusage __user *ru	kernel/exit.c:1655
[285] = "not" implemented -	-	-	-	-	
[286] = "sys_add_key" const char __user *_type	const char __user *_description	const void __user *_payload	size_t plen	key_serial_t destringid	security/keys/keyctl.c:57
[287] = "sys_request_key" const char __user *_type	const char __user *_description	const char __user *_callout_info	key_serial_t destringid	-	security/keys/keyctl.c:149
[288] = "sys_keyctl" int cmd	unsigned long arg2	unsigned long arg3	unsigned long arg4	unsigned long arg5	security/keys/keyctl.c:1338
[289] = "sys_ioprio_set" int which	int who	int ioprio	-	-	fs/ioprio.c:76
[290] = "sys_ioprio_get" int which	int who	-	-	-	fs/ioprio.c:192
[291] = "sys_inotify_init" -	-	-	-	-	fs/notify/inotify/inotify_user.c:680
[292] = "sys_inotify_add_watch" int fd	const char __user *path	u32 mask	-	-	fs/notify/inotify/inotify_user.c:685
[293] = "sys_inotify_rm_watch" int fd	__s32 wd	-	-	-	fs/notify/inotify/inotify_user.c:726
[294] = "sys_migrate_pages" pid_t pid	unsigned long maxnode	const unsigned long __user *from	const unsigned long __user *to	-	mm/mempolicy.c:1273
[295] = "sys_openat" int dfd	const char __user *filename	int flags	int mode	-	fs/open.c:913
[296] = "sys_mkdirat" int dfd	const char __user * pathname	int mode	-	-	fs/namei.c:2093
[297] = "sys_mknodat" int dfd	const char __user * filename	int mode	unsigned dev	-	fs/namei.c:2012
[298] = "sys_fchownat" int dfd	const char __user *filename	uid_t user	gid_t group	int flag	fs/open.c:558
[299] = "sys_futimesat" int dfd	char __user *filename	struct timeval __user *utimes	-	-	fs/utimes.c:191
[300] = "sys_fstatat64" int dfd	char __user *filename	struct stat64 __user *statbuf	int flag	-	fs/stat.c:391
[301] = "sys_unlinkat" int dfd	const char __user * pathname	int flag	-	-	fs/namei.c:2341
[302] = "sys_renameat" int olddfd	const char __user * oldname	int newdfd	const char __user * newname	-	fs/namei.c:2671
[303] = "sys_linkat" int olddfd	const char __user *oldname	int newdfd	const char __user *newname	int flags	fs/namei.c:2470
[304] = "sys_symlinkat" const char __user * oldname	int newdfd	const char __user * newname	-	-	fs/namei.c:2377
[305] = "sys_readlinkat" int dfd	const char __user *path	char __user *buf	int bufsiz	-	fs/stat.c:284
[306] = "sys_fchmodat" int dfd	const char __user * filename	mode_t mode	-	-	fs/open.c:474
[307] = "sys_faccessat" int dfd	const char __user *filename	int mode	-	-	fs/open.c:286
[308] = "sys_pselect6" -	-	-	-	-	fs/select.c:675
[309] = "sys_ppoll" struct pollfd __user *ufds	unsigned int nfds	struct timespec __user *tsp	const sigset_t __user *sigmask	size_t sigsetsize	fs/select.c:950
[310] = "sys_unshare" unsigned long unshare_flags	-	-	-	-	kernel/fork.c:1624
[311] = "sys_set_robust_list" struct robust_list_head __user *head	size_t len	-	-	-	kernel/futex.c:2351
[312] = "sys_get_robust_list" int pid	struct robust_list_head __user * __user *head_ptr	size_t __user *len_ptr	-	-	kernel/futex.c:2373
[313] = "sys_splice" -	-	-	-	-	fs/splice.c:1718
[314] = "sys_sync_file_range" int fd	loff_t offset	loff_t nbytes	unsigned int flags	-	not found:
[315] = "sys_tee" int fdin	int fdout	size_t len	unsigned int flags	-	fs/splice.c:2061
[316] = "sys_vmsplice" int fd	const struct iovec __user *iov	unsigned long nr_segs	unsigned int flags	-	fs/splice.c:1692
[317] = "sys_move_pages" -	-	-	-	-	mm/migrate.c:1075
[318] = "sys_getcpu" unsigned __user *cpu	unsigned __user *node	struct getcpu_cache __user *cache	-	-	kernel/sys.c:1621
[319] = "sys_epoll_pwait" -	-	-	-	-	fs/eventpoll.c:1373
[320] = "sys_utimensat" int dfd	char __user *filename	struct timespec __user *utimes	int flags	-	fs/utimes.c:173
[321] = "sys_signalfd" int ufd	sigset_t __user *user_mask	size_t sizemask	-	-	fs/signalfd.c:265
[322] = "sys_timerfd_create" int clockid	int flags	-	-	-	fs/timerfd.c:164
[323] = "sys_eventfd" unsigned int count	-	-	-	-	fs/eventfd.c:434
[324] = "sys_fallocate" int fd	int mode	loff_t offset	loff_t len	-	not found:
[325] = "sys_timerfd_settime" int ufd	int flags	const struct itimerspec __user *utmr	struct itimerspec __user *otmr	-	fs/timerfd.c:194
[326] = "sys_timerfd_gettime" int ufd	struct itimerspec __user *otmr	-	-	-	fs/timerfd.c:252
[327] = "sys_signalfd4" int ufd	sigset_t __user *user_mask	size_t sizemask	int flags	-	fs/signalfd.c:211
[328] = "sys_eventfd2" unsigned int count	int flags	-	-	-	fs/eventfd.c:409
[329] = "sys_epoll_create1" int flags	-	-	-	-	fs/eventpoll.c:1187
[330] = "sys_dup3" unsigned int oldfd	unsigned int newfd	int flags	-	-	fs/fcntl.c:53
[331] = "sys_pipe2" int __user *fildes	int flags	-	-	-	fs/pipe.c:1101
[332] = "sys_inotify_init1" int flags	-	-	-	-	fs/notify/inotify/inotify_user.c:640
[333] = "sys_preadv" unsigned long fd	const struct iovec __user *vec	unsigned long vlen	unsigned long pos_l	unsigned long pos_h	fs/read_write.c:759
[334] = "sys_pwritev" unsigned long fd	const struct iovec __user *vec	unsigned long vlen	unsigned long pos_l	unsigned long pos_h	fs/read_write.c:784
[335] = "sys_rt_tgsigqueueinfo" pid_t tgid	pid_t pid	int sig	siginfo_t __user *uinfo	-	kernel/signal.c:2437
[336] = "sys_perf_event_open" struct perf_event_attr __user *attr_uptr	pid_t pid	int cpu	int group_fd	unsigned long flags	kernel/perf_event.c:5065
[337] = "sys_recvmmsg" int fd	struct mmsghdr __user *msg	unsigned int vlen	unsigned flags	struct timespec __user *timeout	net/socket.c:2168